/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_15 (
    input z,
    input v,
    input n,
    input [1:0] alufn,
    output reg [15:0] cmp
  );
  
  
  
  always @* begin
    cmp[1+14-:15] = 15'h0000;
    
    case (alufn)
      2'h1: begin
        cmp[0+0-:1] = z;
      end
      2'h2: begin
        cmp[0+0-:1] = n ^ v;
      end
      2'h3: begin
        cmp[0+0-:1] = z | (n ^ v);
      end
      default: begin
        cmp[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
