/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module hardCount_9 (
    input clk,
    input rst,
    input resetCount,
    output reg [23:0] value,
    output reg [15:0] light
  );
  
  
  
  reg [23:0] M_flip_d, M_flip_q = 1'h0;
  reg [5:0] M_count_d, M_count_q = 1'h0;
  
  wire [16-1:0] M_randSeq_sequence;
  reg [6-1:0] M_randSeq_value;
  randomSequence_18 randSeq (
    .value(M_randSeq_value),
    .sequence(M_randSeq_sequence)
  );
  
  always @* begin
    M_count_d = M_count_q;
    M_flip_d = M_flip_q;
    
    M_randSeq_value = M_count_q;
    M_flip_d = M_flip_q + 1'h1;
    value = M_flip_q;
    
    case (M_count_q[0+0-:1])
      1'h0: begin
        light = M_randSeq_sequence;
      end
      1'h1: begin
        light = 16'h0000;
      end
      default: begin
        light = 16'h0000;
      end
    endcase
    if (resetCount) begin
      M_flip_d = 1'h0;
    end else begin
      if (M_flip_q == 24'hffffff) begin
        M_count_d = M_count_q + 1'h1;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_flip_q <= 1'h0;
      M_count_q <= 1'h0;
    end else begin
      M_flip_q <= M_flip_d;
      M_count_q <= M_count_d;
    end
  end
  
endmodule
