/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module delayCount_6 (
    input clk,
    input rst,
    input resetCount,
    output reg [2:0] value,
    output reg [15:0] light
  );
  
  
  
  reg [24:0] M_flip_d, M_flip_q = 1'h0;
  reg [2:0] M_count_d, M_count_q = 1'h0;
  
  always @* begin
    M_count_d = M_count_q;
    M_flip_d = M_flip_q;
    
    M_flip_d = M_flip_q + 1'h1;
    value = M_count_q;
    
    case (M_count_q)
      3'h0: begin
        light = 16'h0000;
      end
      3'h1: begin
        light = 16'hffff;
      end
      3'h2: begin
        light = 16'h0000;
      end
      3'h3: begin
        light = 16'h6ff6;
      end
      3'h4: begin
        light = 16'h0000;
      end
      3'h5: begin
        light = 16'h0660;
      end
      default: begin
        light = 16'h0000;
      end
    endcase
    if (resetCount) begin
      M_flip_d = 1'h0;
      M_count_d = 1'h0;
    end else begin
      if (M_flip_q == 25'h1ffffff) begin
        M_count_d = M_count_q + 1'h1;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_flip_q <= 1'h0;
      M_count_q <= 1'h0;
    end else begin
      M_flip_q <= M_flip_d;
      M_count_q <= M_count_d;
    end
  end
  
endmodule
