/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_17 (
    input [15:0] a,
    input [3:0] b,
    input [1:0] alufn,
    output reg [15:0] shift
  );
  
  
  
  always @* begin
    
    case (alufn)
      2'h0: begin
        shift = a << b;
      end
      2'h1: begin
        shift = a >> b;
      end
      2'h3: begin
        shift = $signed(a) >>> b;
      end
      default: begin
        shift = 16'h0000;
      end
    endcase
  end
endmodule
